baseURL = "https://competent-torvalds-8b0728.netlify.app"
languageCode = "en-us"
title = "C.N.M.B NYC"
theme = "ananke"
enableemoji = true

Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
  background_color_class = "bg-light-purple"
  commentoEnable = true
